name: gitleaks

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
      if: failure()
   
   

    - name: Login to Jira
      uses: atlassian/gajira-login@master
      if: failure()
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Create Jira issue on job failure
      uses: atlassian/gajira-create@master
      if: failure()
      with:
        project: DMAC
        issuetype: Bug
        summary: Congratulations! ${{ github.workflow }} failed in ${{ github.repository }}
        
    - name: Notify Teams
      # You may pin to the exact commit or the version.
      # uses: thechetantalwar/teams-notify@8a78811f5e8f58cdd204efebd79158006428c46b
      uses: thechetantalwar/teams-notify@v2
      if: failure()
      with:
        # WebHook URL of your MS Teams Channel
        teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK }}
        # Message to be sent
        message: Congratulations! ${{github.workflow}} workflow failed successfully in ${{ github.repository }}