# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: NPM commands 
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
#     - run: npm audit 
    - run: npm audit fix --force
    
    - name: Login to Jira
      uses: atlassian/gajira-login@master
      if: failure()
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Create Jira issue on job failure
      uses: atlassian/gajira-create@master
      if: failure()
      with:
        project: DMAC
        issuetype: Bug
        summary: Congratulations! ${{ github.workflow }} failed in ${{ github.repository }}
        
    - name: Notify Teams
      # You may pin to the exact commit or the version.
      # uses: thechetantalwar/teams-notify@8a78811f5e8f58cdd204efebd79158006428c46b
      uses: thechetantalwar/teams-notify@v2
      if: failure()
      with:
        # WebHook URL of your MS Teams Channel
        teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK }}
        # Message to be sent
        message: Congratulations! ${{github.workflow}} workflow failed successfully in ${{ github.repository }}