# This is a basic workflow to help you get started with Actions

name: Semgrep Working

on:
  pull_request: {}
  push:
    branches:
    - main
    - master
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
