# This is a basic workflow to help you get started with Actions

name: Semgrep Working

on:
  pull_request: {}
  push:
    branches:
    - main
    - master
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - name: Semgrep
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        
    - name: Notify Teams
      # You may pin to the exact commit or the version.
      # uses: thechetantalwar/teams-notify@8a78811f5e8f58cdd204efebd79158006428c46b
      uses: thechetantalwar/teams-notify@v2
      if: failure()
      with:
        # WebHook URL of your MS Teams Channel
        teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK }}
        # Message to be sent
        message: Congratulations! ${{github.workflow}} workflow failed successfully in ${{ github.repository }}
