# This is a basic workflow to help you get started with Actions

name: Semgrep Working

on:
  pull_request: {}
  push:
    branches:
    - main
    - master
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - name: Semgrep
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        
      
    - name: Login to Jira
      uses: atlassian/gajira-login@master
      if: failure()
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Create Jira issue on job failure
      uses: atlassian/gajira-create@master
      if: failure()
      with:
        project: DMAC
        issuetype: Bug
        summary: Congratulations! ${{ github.workflow }} failed in ${{ github.repository }}
        
  
